name: microbiome-gnn-disease
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - matplotlib
  - joblib
  - pytorch
  - pytorch-cuda=12.4
  - scikit-learn
  - networkx
  - torchvision
  - xgboost
  - ipykernel
  - python=3.11
  - scipy
  - pandas
  - llvm-openmp
  - jupyter
  - numpy
  - tqdm
  - optuna
